### ISSUE TITLE
Space in feature name is not possible

### ISSUE THREAD

**Issue by HermansJarno** [MicroFocus/bdd2octane#10]
Executing bdd2octane for a feature file with a space in the filename results in a skip since the space is converted to %20 and bdd2octane doesnt recognize this. Is there a configuration that needs to be set to prevent this?

When downloading a gherkin test from alm octane which has spaces in its name, it also copies the spaces like it is in Octane. 

If there is no workarround for this we either need to use PascalCasing in octane, or we always need to download a script, copy its contents to the file without spaces and delete the file with spaces. Because ALM Octane plugin doesn't let you configure the name through the IDE (IntelliJ).

The command line execution log:

`java -jar C:\Dev\bdd2octane\bdd2octane-1.1.2.jar --reportFiles="**/target/surefire-reports/*.*.xml" --featureFiles="**/src/test/resources/features/**/*.feature" --framework="cucumber-jvm" --resultFile="target/bdd2octane-reports/cucumber-jvm-result.xml"

Picked up JAVA_TOOL_OPTIONS: -agentlib:jvmhook
Picked up _JAVA_OPTIONS: -Xrunjvmhook -Xbootclasspath/a:"C:\Program Files (x86)\Micro Focus\Unified Functional Testing\bin\java_shared\classes\jasmine.jar"
All xml files matching pattern "**/target/surefire-reports/*.*.xml":
        target\surefire-reports\TEST-testrunners.RunCucumberTest.xml
All feature files matching pattern "**/src/test/resources/features/**/*.feature":
        src\test\resources\features\example.feature
        src\test\resources\features\webshop\Buy Items_65001.feature
        src\test\resources\features\webshop\contact\DemoBDD2_67003.feature
        src\test\resources\features\webshop\login\Login_64003.feature
        src\test\resources\features\webshop\login\poc_10001.feature
cannot locate a feature file by path:  classpath:features/webshop/Buy%20Items_65001.feature skipping...
8 test case(s) processed
1 test case(s) skipped`

**Comment by nissimshitrit** [comment]
The issue was resolved on latest release 1.1.3
