### ISSUE TITLE
Scenario outline with examples are skipped

### ISSUE THREAD

**Issue by HermansJarno** [MicroFocus/bdd2octane#14]
>>>

Cannot locate a feature file for: Examples skipping ...
Cannot locate a feature file for: Examples skipping ...
Cannot locate a feature file for: Examples skipping ...
Cannot locate a feature file for: Examples skipping ...
7 test case(s) processed
4 test case(s) skipped

>>>

I have 2 Scenario outlines with each 2 examples. It appears they are being skipped by bdd2octane.1.1.3
Is there any solution for this?

Example of a scenario outline being skipped:

Scenario Outline: testuser places orders on phones
	Given user added <phone> to cart
        When user places an order with "valid" credentials
	Then user sees message containing <message>

	Examples:
		| phone 			       | message 				      | 
		| "Samsung Galaxy s6"   | "Your order has been received"    | 
		| "Nokia Lumia 520"       | "Your order has been received"    |

**Comment by micheleh** [comment]
@HermansJarno does the feature file that contains this 'Scenario Outline' has the 'Feature:' keyword at the top of this file?
If it contains the 'Feature:' keyword, is there a name to that feature?

**Comment by HermansJarno** [comment]
@micheleh Yes it does. Full example feature file:

#Auto generated Octane revision tag
@BSPID4004REV0.14.0
Feature: Place orders from cart

	Background:
    	Given "testuserapg" is logged in to the product store
        And user is on "home" page

@TSCID41012
	Scenario Outline: testuserapg places orders on phones
		Given user added <phone> to cart
        When user places an order with "valid" credentials
		Then user sees message containing <message>

	Examples:
		| phone 				| message 							| 
		| "Samsung Galaxy s6"   | "Your order has been received"    | 
		| "Nokia Lumia 520"     | "Your order has been received"    |

**Comment by bingyujin** [comment]
> 

Hi @HermansJarno it seems like the values not are replaced with parameters as <parameter_name> in step-definition itself.
It should be:
Scenario Outline: testuser places orders on <phone>
Given user added to cart
When user places an order with "valid" credentials
Then user sees <message> containing
Examples:
	| phone 				| message 							| 
	| "Samsung Galaxy s6"   | "Your order has been received"    | 
	| "Nokia Lumia 520"     | "Your order has been received"    |

**Comment by HermansJarno** [comment]
@bingyujin i didnt notice that github replaced the <> parameters with empty spaces. And i also understand now why github was putting square boxes arround my step definitions. The 'should be' you defined is how my code is looking. 

So this is how my code looks like:
```

#Auto generated Octane revision tag
@BSPID4004REV0.14.0
Feature: Place orders from cart

Background:
Given "testuser" is logged in to the product store
And user is on "home" page

@TSCID41012
	Scenario Outline: testuser places orders on phones
	Given user added <phone> to cart
        When user places an order with "valid" credentials
	Then user sees message containing <message>

Examples:
	| phone 		| message 			| 
	| "Samsung Galaxy s6"   | "Your order has been received"    | 
	| "Nokia Lumia 520"     | "Your order has been received"    | 
```

**Comment by HermansJarno** [comment]
Commando i use:

java -jar C:\Dev\bdd2octane\bdd2octane-1.1.3.jar --reportFiles="**/target/surefire-reports/*.*.xml" --featureFiles="**/src/test/resources/**/features/**/*.feature" --framework="cucumber-jvm" --resultFile="target/bdd2octane-reports/cucumber-jvm-result.xml"

The pom file showing the framework versions (sensitive data is replaced with dots in both files):
[pom.xml.txt](https://github.com/MicroFocus/bdd2octane/files/12454293/pom.xml.txt)

The surefire-report used:
[TEST-bddoctane.RunCucumberTest.xml.txt](https://github.com/MicroFocus/bdd2octane/files/12454294/TEST-bddoctane.RunCucumberTest.xml.txt)

I see now that the problem is in the sure-fire report. Its till now unclear for me why sure-fire report is putting Examples as classname instead of the Scenario outline. If you have suggestions im happy to hear. Conclusion is that the problem is not linked to the bdd2octane plugin. Sorry for opening an issue here. If you have no suggestions on how to fix the sure-fire issue, then issue can be closed.

**Comment by bingyujin** [comment]
> Commando i use:
> 
> java -jar C:\Dev\bdd2octane\bdd2octane-1.1.3.jar --reportFiles="**/target/surefire-reports/_._.xml" --featureFiles="**/src/test/resources/**/features/**/*.feature" --framework="cucumber-jvm" --resultFile="target/bdd2octane-reports/cucumber-jvm-result.xml"
> 
> The pom file showing the framework versions (sensitive data is replaced with dots in both files): [pom.xml.txt](https://github.com/MicroFocus/bdd2octane/files/12454293/pom.xml.txt)
> 
> The surefire-report used: [TEST-bddoctane.RunCucumberTest.xml.txt](https://github.com/MicroFocus/bdd2octane/files/12454294/TEST-bddoctane.RunCucumberTest.xml.txt)
> 
> I see now that the problem is in the sure-fire report. Its still unclear for me why sure-fire report is putting Examples as classname instead of the Scenario outline. If you have suggestions im happy to hear. Conclusion is that the problem is not linked to the bdd2octane plugin. Sorry for opening an issue here. If you have no suggestions on how to fix the sure-fire issue, then issue can be closed.

@HermansJarno I just think of a possibility that surefire can't parse your case because the 2 testcases will be the same in surefire as feature name and scenario name is the same.
<testcase name="Place orders from cart" classname="testuser places orders on phones" time="0.008">
I recommend you to change the feature like:
#Auto generated Octane revision tag
@BSPID4004REV0.14.0
Feature: Place orders from cart

Background:
Given "testuser" is logged in to the product store
And user is on "home" page

@TSCID41012
	Scenario Outline: testuser places orders on <name>phones
	Given user added \<phone\> to cart
        When user places an order with "valid" credentials
	Then user sees message containing \<message\>

Examples:
	|name| phone 		| message 			| 
	|name1| "Samsung Galaxy s6"   | "Your order has been received"    | 
	|name2| "Nokia Lumia 520"     | "Your order has been received"    | 

so in surefire it will be different for 2 testcases
<testcase name="Place orders from cart" classname="testuser places orders on name1 phones" time="0.008">
<testcase name="Place orders from cart" classname="testuser places orders on name2 phones" time="0.008">

If it doesn't work, please try to upgrade or downgrade the version of maven-surefire-plugin.

**Comment by HermansJarno** [comment]
@bingyujin thanks for the suggestion but this didnt help. It's still reporting as name Example#1.1 and classname Examples. i'll try to switch between maven-surefire versions.

**Comment by HermansJarno** [comment]
@bingyujin i've tried a suggestion from stackoverflow, namely to add cucumber.junit-platform.naming-strategy=long to the pom. https://stackoverflow.com/questions/75550695/surefire-plugin-reports-from-cucumber-test-with-reruns-on-examples

This causes the tests names to be unique, but unfortunately bdd2octane is unable to convert those results to octane.
Not only for the Scenario outlines but also for the other tests.

Could it be that the way surefire reports the tests and how bdd2octane converts those results, that this will never work for scenario outlines?

**Comment by HermansJarno** [comment]
@bingyujin i also tried the suggestion of changing the maven-surefire-plugin version. This did not help. The Scenario outlines are still reported as examples.

**Comment by HermansJarno** [comment]
@bingyujin i'm trying to apply your suggestion on replacing cucumber-junit-platform-engine with cucumber-junit.

When i try to import  io.cucumber.junit.CucumberOptions i notice that CucumberOptions isnt a package within the junit package, it's unable to resolve the symbol.

If I investigate further I notice that @CucumberOptions is a part of JUnit4, while our team is on JUnit5. For JUnit5 its recommended to use the cucumber-junit-platform-engine.

Am i correct that we should downgrade to junit4 if we want to get this working with the current version of bdd2octane?

**Comment by bingyujin** [comment]
> @bingyujin i'm trying to apply your suggestion on replacing cucumber-junit-platform-engine with cucumber-junit.
> 
> When i try to import io.cucumber.junit.CucumberOptions i notice that CucumberOptions isnt a package within the junit package, it's unable to resolve the symbol.
> 
> If I investigate further I notice that @CucumberOptions is a part of JUnit4, while our team is on JUnit5. For JUnit5 its recommended to use the cucumber-junit-platform-engine.
> 
> Am i correct that we should downgrade to junit4 if we want to get this working with the current version of bdd2octane?

Yes, if you'd like to try this solution, here is my example: https://github.com/bingyujin/cucumber-jvm-maven/tree/version7.0.0

**Comment by HermansJarno** [comment]
@bingyujin is it possible to completely support junit5 with it's different way of reporting cucumber results? Or is there a good reason not to?

**Comment by HermansJarno** [comment]
@bingyujin do you have an update on junit5? I got time in my current sprint so i'll test if https://github.com/bingyujin/cucumber-jvm-maven/tree/version7.0.0 works for our needs.

**Comment by HermansJarno** [comment]
@bingyujin i've tried the example you suggested. It solves the issue with the scenario outlines but it also introduces new issues for us. Is it possible for you or teammembers to investigate if you can get JUnit5 working?

**Comment by bingyujin** [comment]
> @bingyujin i've tried the example you suggested. It solves the issue with the scenario outlines but it also introduces new issues for us. Is it possible for you or teammembers to investigate if you can get JUnit5 working?

@nissimshitrit could you please investigate if we can get JUnit5 working to address the new issues we encountered?

**Comment by nissimshitrit** [comment]
This is a known issue and we have open issue on we will handle when it get prioritized

**Comment by HermansJarno** [comment]
@nissimshitrit do you have an idea when this will get prioritized?

**Comment by nissimshitrit** [comment]
@HermansJarno we don't have scheduled data on when it will be handled, it on our backlog when it will be prioritize we will handle , currently I cannot estimate when it will happen

**Comment by nissimshitrit** [comment]
Hi @HermansJarno , I tried to check your input with generating Junit report on tests executing and using this Junit report and input to bdd2Octane tool, and it seems to work correctly.
I added this annotation to test configuration in order to create the Junit report
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "junit:target/cucumber-reports.xml")
Can you please try it and update if worked for you?
Thanks,
Nissim

**Comment by HermansJarno** [comment]
@nissimshitrit how does your pom look like? Because i dont get it working with Junit5.

**Comment by nissimshitrit** [comment]
@HermansJarno , I used the exact same pom,xml file that you provided, the only think added is that report will be generated as junit and add new output file location.
This is the pom file content I used when test it:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xmlns="http://maven.apache.org/POM/4.0.0"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>.......</groupId>
	<artifactId>bddoctane</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>jar</packaging>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.cucumber</groupId>
				<artifactId>cucumber-bom</artifactId>
				<version>7.13.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.junit</groupId>
				<artifactId>junit-bom</artifactId>
				<version>5.9.3</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit-platform-engine</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-suite</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<encoding>UTF-8</encoding>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.1.2</version>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by nissimshitrit** [comment]
@HermansJarno 
I understand the default result of maven create minimal information regarding tests example that can be use by current bdd2Octane tool, but the bdd2Octane tool is expect to get Junit report.
On cucumber 7 there different way to define Junit report , and it be adding configuration to test class, this for example what configure when executed test that you mentioned here
For example this is how my test class configuration looks like( I marked to Junit report configuration):
@Suite
@IncludeEngines("cucumber")
@SelectClasspathResource("com/mytest/placeorder")
@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "com.mytest.placeorder")
@ConfigurationParameter(key = PLUGIN_PROPERTY_NAME, value = "junit:target/cucumber-reports.xml")
public class CucumberTest {

}


As a result this the report file created after test executed and I use this report as input for bdd2Octane tool

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<testsuite errors="0" failures="0" name="io.cucumber.core.plugin.JUnitFormatter" skipped="0" tests="2" time="0.026">
    <testcase classname="Place orders from cart" name="testuser places orders on phones" time="0">
        <system-out>
            <![CDATA[Given "testuser" is logged in to the product store..........................passed
And user is on "home" page..................................................passed
Given user added "Samsung Galaxy s6" to cart................................passed
When user places an order with "valid" credentials..........................passed
Then user sees message containing "Your order has been received"............passed
]]>
        </system-out>
    </testcase>
    <testcase classname="Place orders from cart" name="testuser places orders on phones 2" time="0">
        <system-out>
            <![CDATA[Given "testuser" is logged in to the product store..........................passed
And user is on "home" page..................................................passed
Given user added "Nokia Lumia 520" to cart..................................passed
When user places an order with "valid" credentials..........................passed
Then user sees message containing "Your order has been received"............passed
]]>
        </system-out>
    </testcase>
</testsuite>


Can you please check if this confuguration works for you?

**Comment by HermansJarno** [comment]
@nissimshitrit if i convert target/cucumber-reports.xml with bdd2octane tool, then all scenarios are converted as it should. Nice.

**But**, when sent to octane with jenkins ALM Octane Cucumber test reporter, Octane seems not to be able to read those results.

I've compared the conversion of surefire-report with that of junit:target/cucumber-reports and the syntax looks the same, except for the scenarios with examples that do get converted now. These now have an outlineIndex. 

If i only change the conversion of --reportFiles="**/target/cucumber-results/*.xml" to --reportFiles="**/target/surefire-reports/*.xml" and also pass it to the ALM Octane Cucumber test reporter, then the results do get communicated (without the scenarios that contain examples ofcourse).

Is this something that should be fixed in the bdd2octane tool or octane itself? We're on octane 16.2.100.43

**Comment by nissimshitrit** [comment]
@HermansJarno the outlineIndex is expected on scenarios that have example.
What happen if you set the junit report as input for bdd2Octane?
You can add to Octane pipeline "follow" to get BDD test injection failure and understand why it not injected.
it can be done be getting into pipeline view, and then select follow

**Comment by HermansJarno** [comment]
@nissimshitrit ill come back to you when this is resolved at our side.

**Comment by micheleh** [comment]
@HermansJarno, any news from your side?
