### ISSUE TITLE
Question: What is the Azure Devops alternative for this plugin?

### ISSUE THREAD

**Issue by HermansJarno** [MicroFocus/bdd2octane#16]
At my customer we use both jenkins and azure devops.
For jenkins i have integrated octane with https://plugins.jenkins.io/hp-application-automation-tools-plugin/ and this plugin.

For azure devops we use https://marketplace.visualstudio.com/items?itemName=ALMOctane.alm-octane-integration-public but it's not clear how to transfer the gherkin results since bdd2octane is made for the jenkins integration. Is this the right place to ask?

**Comment by nissimshitrit** [comment]
You can bdd2Octane tool with command line , and then add the to Azure end task on "Cucumber report destination path" the report that generated by bdd2Octane tool
in my Azure those are the values
CMD: 
java -jar c:/bdd2octane/bdd2octane-1.1.3.jar --reportFiles=/target/surefire-reports/*.xml --featureFiles=/src/test/resources/F1/*.feature --framework=cucumber-jvm --resultFile=bdd2OctaneResult/cucumber-jvm-result.xml
End task configuration: 
CucumberReportPath: bdd2OctaneResult

**Comment by HermansJarno** [comment]
@nissimshitrit so the CucumberReportPath should point to the folder bdd2OctaneResult, not a regex for the xml files?

**Comment by HermansJarno** [comment]
@nissimshitrit already got my answer, indeed the folder. Thanks! Closing question.
